services:
  postgres-restoran:
    image: postgres:15
    container_name: postgres-restoran
    environment:
      POSTGRES_DB: restoran
      POSTGRES_USER: restoran
      POSTGRES_PASSWORD: restoran
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - restoran-network

  restoran-app:
    build: .
    container_name: restoran-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres-restoran
    networks:
      - restoran-network
volumes:
  postgres-data:

networks:
  restoran-network:
